### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by dhafitf** [dhafitf/dhafit.xyz#8]
## Tasks

- [x] Migrate to Tailwind CSS #9 
- [x] Fix type interface #9 
- [x] Improve SEO #10 
- [x] Add top played spotify #11
